### ISSUE TITLE
Carbonetes lens extension doesn't work with Lens 5.2 version and is showing as Incompatible.

### ISSUE THREAD

**Issue by Akulshr** [carbonetes/carbonetes-lens-extension#1]
I am trying to install Carbonetes lens extension on Lens version 5.2.7-latest.20211110.1. I am seeing status as Incompatible.

![image](https://user-images.githubusercontent.com/42188236/141350715-261460d0-8e0e-470b-a89d-a74f64399ca6.png)

**Comment by carbonetes** [comment]
Hi @Akulshr, sorry for the late response. This is already fixed in the latest [release](https://github.com/carbonetes/carbonetes-lens-extension/releases/tag/v0.1.5).
